<?php
/**
 * Database Seeder for Expo Tree Exhibitions
 * Seeds Admin User and All Events from the Excel Data
 */

require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/functions.php';

echo "=== Seeding Expo Tree Database ===\n";

// 1. Seed Admin User
$adminUser = 'admin';
$adminEmail = 'admin@expotreeexhibitions.com';
$adminPass = 'Admin@ExpoTree2026';
$passwordHash = password_hash($adminPass, PASSWORD_BCRYPT);

$checkAdmin = $pdo->prepare("SELECT id FROM admin_users WHERE username = ?");
$checkAdmin->execute([$adminUser]);
if (!$checkAdmin->fetch()) {
    $insAdmin = $pdo->prepare("INSERT INTO admin_users (username, email, password_hash, full_name, role) VALUES (?, ?, ?, ?, ?)");
    $insAdmin->execute([$adminUser, $adminEmail, $passwordHash, 'Expo Tree Administrator', 'admin']);
    echo "[OK] Default Admin created (Username: admin | Password: {$adminPass})\n";
} else {
    // Update password hash to ensure credentials match
    $upAdmin = $pdo->prepare("UPDATE admin_users SET password_hash = ? WHERE username = ?");
    $upAdmin->execute([$passwordHash, $adminUser]);
    echo "[OK] Admin user password updated\n";
}

// 2. Events from the Excel Sheet + Flagship Exhibitions
$events = [
    [
        'title' => 'Lucerna Towers Corporate Lifestyle Carnival',
        'date_display' => '13 Oct 2026',
        'start_date' => '2026-10-13',
        'end_date' => '2026-10-13',
        'venue' => 'Lucerna Towers',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '3,000+ Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => '300 RS',
        'price_shopping_canopy' => 5000,
        'price_shopping_table1' => 3500,
        'price_shopping_table2' => 4000,
        'price_food_canopy' => 5000,
        'price_food_table2' => 4500,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 5000,
        'total_stalls' => 20,
        'available_stalls' => 17,
        'booked_stalls' => 3,
        'image_url' => 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
        'description' => 'Exclusive corporate festive exhibition at Lucerna Towers Noida. Direct access to 3,000 corporate professionals looking for festive gifting, apparel, perfumes, jewellery & food stalls.',
        'is_featured' => 1
    ],
    [
        'title' => 'Smartworks Noida Premium Tech Park Popup - Day 1',
        'date_display' => '13 Oct 2026',
        'start_date' => '2026-10-13',
        'end_date' => '2026-10-13',
        'venue' => 'Smartworks Co-Working Hub',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '3,000+ Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => null,
        'price_shopping_table1' => 6000,
        'price_shopping_table2' => 7000,
        'price_food_canopy' => null,
        'price_food_table2' => null,
        'price_promotional' => '10K onwards',
        'daily_stall_price' => 6000,
        'total_stalls' => 10,
        'available_stalls' => 8,
        'booked_stalls' => 2,
        'image_url' => 'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&w=800&q=80',
        'description' => 'Fully air-conditioned indoor corporate market inside Smartworks, Sector 125 Noida. High-purchasing power IT & management staff.',
        'is_featured' => 0
    ],
    [
        'title' => 'Smartworks Noida Premium Tech Park Popup - Day 2',
        'date_display' => '14 Oct 2026',
        'start_date' => '2026-10-14',
        'end_date' => '2026-10-14',
        'venue' => 'Smartworks Co-Working Hub',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '3,000+ Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => null,
        'price_shopping_table1' => 6000,
        'price_shopping_table2' => 7000,
        'price_food_canopy' => null,
        'price_food_table2' => null,
        'price_promotional' => '10K onwards',
        'daily_stall_price' => 6000,
        'total_stalls' => 10,
        'available_stalls' => 9,
        'booked_stalls' => 1,
        'image_url' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
        'description' => 'Mid-week festive shopping extravaganza for tech & corporate employees at Smartworks Noida.',
        'is_featured' => 0
    ],
    [
        'title' => 'Bestech Park View Spa Next Festive Society Mela',
        'date_display' => '17 Oct 2026',
        'start_date' => '2026-10-17',
        'end_date' => '2026-10-17',
        'venue' => 'Bestech Park View Spa Next, Sector 67',
        'city' => 'Gurugram',
        'state' => 'Haryana',
        'footfall' => '570+ Elite Families',
        'event_type' => 'Society',
        'gentry' => 'Middle Class',
        'timings' => '4:00 PM - 10:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => '300 RS',
        'price_shopping_canopy' => 4000,
        'price_shopping_table1' => 3000,
        'price_shopping_table2' => 3500,
        'price_food_canopy' => 6000,
        'price_food_table2' => 5000,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 4000,
        'total_stalls' => 30,
        'available_stalls' => 24,
        'booked_stalls' => 6,
        'image_url' => 'https://images.unsplash.com/photo-1577900232427-18219b9166a0?auto=format&fit=crop&w=800&q=80',
        'description' => 'Pre-Diwali evening festive bazaar in premium high-rise society. Ideal for women lehengas, imitation jewellery, footwear, kidswear, bakery & food stalls.',
        'is_featured' => 1
    ],
    [
        'title' => 'M3M Skyheights Luxury Pre-Diwali Trunk Show',
        'date_display' => '17 Oct 2026',
        'start_date' => '2026-10-17',
        'end_date' => '2026-10-17',
        'venue' => 'M3M Skyheights Clubhouse & Lawns',
        'city' => 'Gurugram',
        'state' => 'Haryana',
        'footfall' => '1,000+ Premium Families',
        'event_type' => 'Society',
        'gentry' => 'Premium Class',
        'timings' => '4:00 PM - 10:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => '300 RS',
        'price_shopping_canopy' => 8000,
        'price_shopping_table1' => 5000,
        'price_shopping_table2' => 6000,
        'price_food_canopy' => 7000,
        'price_food_table2' => 5000,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 8000,
        'total_stalls' => 20,
        'available_stalls' => 14,
        'booked_stalls' => 6,
        'image_url' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        'description' => 'Ultra-luxury residential mela at M3M Golf Course Extension Road. High-spending residents eager for designer jewellery, dry fruits, home decor & couture.',
        'is_featured' => 1
    ],
    [
        'title' => 'Ireo Victory Valley 3-Day Grand Festive Extravaganza',
        'date_display' => '18-19-20 Oct 2026',
        'start_date' => '2026-10-18',
        'end_date' => '2026-10-20',
        'venue' => 'Ireo Victory Valley Grand Central Lawns, Sector 67',
        'city' => 'Gurugram',
        'state' => 'Haryana',
        'footfall' => '800+ Affluent Families',
        'event_type' => 'Society',
        'gentry' => 'Premium Class',
        'timings' => '4:00 PM - 10:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => '300 RS',
        'price_shopping_canopy' => 6000,
        'price_shopping_table1' => 4000,
        'price_shopping_table2' => 5000,
        'price_food_canopy' => 7000,
        'price_food_table2' => 6000,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 6000,
        'total_stalls' => 25,
        'available_stalls' => 18,
        'booked_stalls' => 7,
        'image_url' => 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        'description' => 'Grand 3-day weekend festive market in Gurugram’s tallest residential enclave. Massive crowd footfall across 3 days.',
        'is_featured' => 1
    ],
    [
        'title' => 'Ireo City Central Luxury Mall Festive Flea',
        'date_display' => '19-20 Oct 2026',
        'start_date' => '2026-10-19',
        'end_date' => '2026-10-20',
        'venue' => 'Ireo City Central Mall Boulevard, Sector 59',
        'city' => 'Gurugram',
        'state' => 'Haryana',
        'footfall' => '1,000+ Daily Visitors',
        'event_type' => 'Mall',
        'gentry' => 'Premium Class',
        'timings' => '10:00 AM - 10:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'Layout blueprint provided',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 6000,
        'price_shopping_table1' => null,
        'price_shopping_table2' => null,
        'price_food_canopy' => 6000,
        'price_food_table2' => null,
        'price_promotional' => '10K onwards',
        'daily_stall_price' => 6000,
        'total_stalls' => 10,
        'available_stalls' => 7,
        'booked_stalls' => 3,
        'image_url' => 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=800&q=80',
        'description' => 'Prime high-street shopping boulevard inside Ireo City Central. Strategic assigned canopy layouts with full day footfall.',
        'is_featured' => 1
    ],
    [
        'title' => 'Stellar 1425 Corporate Diwali Bazaar',
        'date_display' => '27 Oct 2026',
        'start_date' => '2026-10-27',
        'end_date' => '2026-10-27',
        'venue' => 'Stellar 1425 Atrium, Sector 142',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '5,000+ Corporate Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => null,
        'price_shopping_table1' => 5000,
        'price_shopping_table2' => 6000,
        'price_food_canopy' => null,
        'price_food_table2' => null,
        'price_promotional' => '10K onwards',
        'daily_stall_price' => 5000,
        'total_stalls' => 10,
        'available_stalls' => 8,
        'booked_stalls' => 2,
        'image_url' => 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        'description' => 'Prominent IT corridor tech park along Noida-Greater Noida Expressway. Pre-Diwali corporate gifting rush.',
        'is_featured' => 0
    ],
    [
        'title' => 'Stellar IT Park Mega Tech Hub Exhibition',
        'date_display' => '27-28 Oct 2026',
        'start_date' => '2026-10-27',
        'end_date' => '2026-10-28',
        'venue' => 'Stellar IT Park Open Plaza, Sector 62',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '12,000+ Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => '300 RS',
        'price_shopping_canopy' => 6000,
        'price_shopping_table1' => null,
        'price_shopping_table2' => null,
        'price_food_canopy' => 5000,
        'price_food_table2' => 4000,
        'price_promotional' => '20k onwards',
        'daily_stall_price' => 6000,
        'total_stalls' => 20,
        'available_stalls' => 15,
        'booked_stalls' => 5,
        'image_url' => 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=800&q=80',
        'description' => 'Massive 2-day outdoor carnival with 12,000 corporate footfall. High demand for apparel, dry fruit hampers, organic cosmetics & live food.',
        'is_featured' => 1
    ],
    [
        'title' => 'Stellar 1423 Tech Corridor Corporate Exhibition',
        'date_display' => '28 Oct 2026',
        'start_date' => '2026-10-28',
        'end_date' => '2026-10-28',
        'venue' => 'Stellar 1423 Ground Concourse, Sector 142',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '5,000+ Corporate Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => null,
        'price_shopping_table1' => 5000,
        'price_shopping_table2' => 6000,
        'price_food_canopy' => null,
        'price_food_table2' => null,
        'price_promotional' => '10K onwards',
        'daily_stall_price' => 5000,
        'total_stalls' => 10,
        'available_stalls' => 8,
        'booked_stalls' => 2,
        'image_url' => 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80',
        'description' => 'High-end corporate building mela right before Diwali vacation. Ideal for scented candles, luxury chocolates, perfumes & handicrafts.',
        'is_featured' => 0
    ],
    [
        'title' => 'M3M Skyheights Dhanteras Festive Evening Bazaar',
        'date_display' => '30 Oct 2026',
        'start_date' => '2026-10-30',
        'end_date' => '2026-10-30',
        'venue' => 'M3M Skyheights Poolside Lawns, Sector 65',
        'city' => 'Gurugram',
        'state' => 'Haryana',
        'footfall' => '1,000+ Premium Families',
        'event_type' => 'Society',
        'gentry' => 'Premium Class',
        'timings' => '4:00 PM - 10:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => '300 RS',
        'price_shopping_canopy' => 8000,
        'price_shopping_table1' => 5000,
        'price_shopping_table2' => 6000,
        'price_food_canopy' => 7000,
        'price_food_table2' => 5000,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 8000,
        'total_stalls' => 20,
        'available_stalls' => 13,
        'booked_stalls' => 7,
        'image_url' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        'description' => 'Dhanteras special luxury society market with peak shopping fervor for 92.5 silver jewellery, festive pooja decor, dry fruits & sweets.',
        'is_featured' => 1
    ],
    [
        'title' => 'The Nile Gurugram Post-Diwali Weekend Mela',
        'date_display' => '01 Nov 2026',
        'start_date' => '2026-11-01',
        'end_date' => '2026-11-01',
        'venue' => 'The Nile Society Central Amphitheatre, Sohna Road',
        'city' => 'Gurugram',
        'state' => 'Haryana',
        'footfall' => '450+ Active Families',
        'event_type' => 'Society',
        'gentry' => 'Middle Class',
        'timings' => '4:00 PM - 10:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 6000,
        'price_shopping_table1' => 4000,
        'price_shopping_table2' => 5000,
        'price_food_canopy' => 7000,
        'price_food_table2' => 5000,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 6000,
        'total_stalls' => 20,
        'available_stalls' => 16,
        'booked_stalls' => 4,
        'image_url' => 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
        'description' => 'Cozy family-centric post-festive gathering with high interest in winter wear, shawls, pottery, wooden toys & bakery items.',
        'is_featured' => 0
    ],
    [
        'title' => 'Stellar 1425 Winter Lifestyle Kickoff',
        'date_display' => '03 Nov 2026',
        'start_date' => '2026-11-03',
        'end_date' => '2026-11-03',
        'venue' => 'Stellar 1425 Concourse, Sector 142',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '5,000+ Corporate Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => null,
        'price_shopping_table1' => 5000,
        'price_shopping_table2' => 6000,
        'price_food_canopy' => null,
        'price_food_table2' => null,
        'price_promotional' => '10K onwards',
        'daily_stall_price' => 5000,
        'total_stalls' => 10,
        'available_stalls' => 8,
        'booked_stalls' => 2,
        'image_url' => 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80',
        'description' => 'Winter collection debut popup for corporate employees. Handbags, perfumes, winter apparel & stationery.',
        'is_featured' => 0
    ],
    [
        'title' => 'Lucerna Towers 2-Day Winter Carnival',
        'date_display' => '3-4 Nov 2026',
        'start_date' => '2026-11-03',
        'end_date' => '2026-11-04',
        'venue' => 'Lucerna Towers Plaza, Sector 125',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '15,000+ Corporate Employees',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 5000,
        'price_shopping_table1' => null,
        'price_shopping_table2' => null,
        'price_food_canopy' => 5000,
        'price_food_table2' => 4500,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 5000,
        'total_stalls' => 20,
        'available_stalls' => 14,
        'booked_stalls' => 6,
        'image_url' => 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&w=800&q=80',
        'description' => 'Massive 2-day outdoor tech carnival with over 15,000 footfall across leading multinational offices.',
        'is_featured' => 1
    ],
    [
        'title' => 'Urbtech Trade Centre Corporate Lifestyle Mela',
        'date_display' => '04 Nov 2026',
        'start_date' => '2026-11-04',
        'end_date' => '2026-11-04',
        'venue' => 'Urbtech Trade Centre Courtyard, Sector 132',
        'city' => 'Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '3,000+ Corporate Staff',
        'event_type' => 'Corporate',
        'gentry' => 'Middle Class',
        'timings' => '10:00 AM - 8:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 5000,
        'price_shopping_table1' => null,
        'price_shopping_table2' => null,
        'price_food_canopy' => 5000,
        'price_food_table2' => 4500,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 5000,
        'total_stalls' => 20,
        'available_stalls' => 17,
        'booked_stalls' => 3,
        'image_url' => 'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?auto=format&fit=crop&w=800&q=80',
        'description' => 'Corporate lifestyle exhibition at Sector 132 expressway corporate park.',
        'is_featured' => 0
    ],
    [
        'title' => 'Central Park Flower Valley Grand Winter Carnival',
        'date_display' => '04 Nov 2026',
        'start_date' => '2026-11-04',
        'end_date' => '2026-11-04',
        'venue' => 'Central Park Flower Valley Clubhouse & Grand Lawns',
        'city' => 'Gurugram',
        'state' => 'Haryana',
        'footfall' => '2,000+ Luxury Families',
        'event_type' => 'Society',
        'gentry' => 'Premium Class',
        'timings' => '4:00 PM - 10:00 PM',
        'location_type' => 'Outdoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 10000,
        'price_shopping_table1' => null,
        'price_shopping_table2' => null,
        'price_food_canopy' => null,
        'price_food_table2' => null,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 10000,
        'total_stalls' => 30,
        'available_stalls' => 22,
        'booked_stalls' => 8,
        'image_url' => 'https://images.unsplash.com/photo-1577900232427-18219b9166a0?auto=format&fit=crop&w=800&q=80',
        'description' => 'One of Gurugram’s largest ultra-luxury township exhibitions with high Net-Worth residents.',
        'is_featured' => 1
    ],
    // Flagship Mega Exhibition Hubs
    [
        'title' => 'South Delhi Autumn Fashion & Luxury Popup',
        'date_display' => '07-08 Nov 2026',
        'start_date' => '2026-11-07',
        'end_date' => '2026-11-08',
        'venue' => 'The Grand Pavilion, Vasant Kunj / Saket Hub',
        'city' => 'Delhi',
        'state' => 'Delhi NCR',
        'footfall' => '18,000+ Affluent Shoppers',
        'event_type' => 'Mall',
        'gentry' => 'Premium Class',
        'timings' => '11:30 AM - 9:30 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'Layout blueprint provided',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 8500,
        'price_shopping_table1' => 5500,
        'price_shopping_table2' => 7000,
        'price_food_canopy' => 8000,
        'price_food_table2' => 6000,
        'price_promotional' => '15k onwards',
        'daily_stall_price' => 8500,
        'total_stalls' => 45,
        'available_stalls' => 35,
        'booked_stalls' => 10,
        'image_url' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        'description' => 'South Delhi haute couture trunk show. Designer silk lehengas, Polki & diamond jewellery, home decor and tarot readings in air-conditioned grand pavilion.',
        'is_featured' => 1
    ],
    [
        'title' => 'Royal Winter & Wedding Trunk Show Faridabad',
        'date_display' => '21-22 Nov 2026',
        'start_date' => '2026-11-21',
        'end_date' => '2026-11-22',
        'venue' => 'Radisson Blu Grand Ballroom & Lawns',
        'city' => 'Faridabad',
        'state' => 'Haryana',
        'footfall' => '15,000+ Wedding Shoppers',
        'event_type' => 'Exhibition',
        'gentry' => 'Premium Class',
        'timings' => '11:00 AM - 9:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'Layout blueprint provided',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 7500,
        'price_shopping_table1' => 4500,
        'price_shopping_table2' => 6000,
        'price_food_canopy' => 7000,
        'price_food_table2' => 5000,
        'price_promotional' => '12k onwards',
        'daily_stall_price' => 7500,
        'total_stalls' => 35,
        'available_stalls' => 28,
        'booked_stalls' => 7,
        'image_url' => 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        'description' => 'Wedding season trunk show in 5-star Radisson Blu ballroom. Bridal trousseau, footwear, luxury gifting & skincare.',
        'is_featured' => 1
    ],
    [
        'title' => 'Delhi NCR Artisan & Handicrafts Carnival Ghaziabad',
        'date_display' => '05-06 Dec 2026',
        'start_date' => '2026-12-05',
        'end_date' => '2026-12-06',
        'venue' => 'Mahagun Metro Mall Atrium, Vaishali',
        'city' => 'Ghaziabad',
        'state' => 'Uttar Pradesh',
        'footfall' => '20,000+ Weekend Shoppers',
        'event_type' => 'Mall',
        'gentry' => 'Middle Class',
        'timings' => '11:00 AM - 10:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'First come first serve',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 6000,
        'price_shopping_table1' => 4000,
        'price_shopping_table2' => 5000,
        'price_food_canopy' => 6500,
        'price_food_table2' => 4500,
        'price_promotional' => '10k onwards',
        'daily_stall_price' => 6000,
        'total_stalls' => 30,
        'available_stalls' => 25,
        'booked_stalls' => 5,
        'image_url' => 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
        'description' => 'Handmade pottery, crochet, organic soaps, home furnishings and live craft workshops inside Vaishali premier mall.',
        'is_featured' => 1
    ],
    [
        'title' => 'Grand Christmas & New Year Lifestyle Expo Greater Noida',
        'date_display' => '19-20 Dec 2026',
        'start_date' => '2026-12-19',
        'end_date' => '2026-12-20',
        'venue' => 'India Expo Centre & Mart Hub',
        'city' => 'Greater Noida',
        'state' => 'Uttar Pradesh',
        'footfall' => '35,000+ Mega Crowd',
        'event_type' => 'Exhibition',
        'gentry' => 'Premium Class',
        'timings' => '11:00 AM - 10:00 PM',
        'location_type' => 'Indoors',
        'layout_type' => 'Layout blueprint provided',
        'fan_charge' => 'Included',
        'price_shopping_canopy' => 9000,
        'price_shopping_table1' => 6000,
        'price_shopping_table2' => 7500,
        'price_food_canopy' => 8500,
        'price_food_table2' => 6500,
        'price_promotional' => '20k onwards',
        'daily_stall_price' => 9000,
        'total_stalls' => 60,
        'available_stalls' => 45,
        'booked_stalls' => 15,
        'image_url' => 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=800&q=80',
        'description' => 'Year-end mega extravaganza at India Expo Mart with giant kids play zone, celebrity guests, all 16 categories and huge footfall.',
        'is_featured' => 1
    ]
];

$stmt = $pdo->prepare("
    INSERT INTO events (
        title, slug, category, event_type, start_date, end_date, date_display,
        venue, city, state, footfall, gentry, timings, location_type,
        layout_type, fan_charge, price_shopping_canopy, price_shopping_table1,
        price_shopping_table2, price_food_canopy, price_food_table2, price_promotional,
        daily_stall_price, total_stalls, available_stalls, booked_stalls,
        image_url, description, is_featured, status, source
    ) VALUES (
        :title, :slug, :category, :event_type, :start_date, :end_date, :date_display,
        :venue, :city, :state, :footfall, :gentry, :timings, :location_type,
        :layout_type, :fan_charge, :price_shopping_canopy, :price_shopping_table1,
        :price_shopping_table2, :price_food_canopy, :price_food_table2, :price_promotional,
        :daily_stall_price, :total_stalls, :available_stalls, :booked_stalls,
        :image_url, :description, :is_featured, 'active', 'admin'
    )
    ON DUPLICATE KEY UPDATE
        date_display = VALUES(date_display),
        daily_stall_price = VALUES(daily_stall_price),
        price_shopping_canopy = VALUES(price_shopping_canopy),
        price_shopping_table1 = VALUES(price_shopping_table1),
        price_shopping_table2 = VALUES(price_shopping_table2),
        price_food_canopy = VALUES(price_food_canopy),
        price_food_table2 = VALUES(price_food_table2),
        price_promotional = VALUES(price_promotional),
        footfall = VALUES(footfall),
        gentry = VALUES(gentry),
        timings = VALUES(timings),
        status = 'active'
");

$insertedCount = 0;
foreach ($events as $e) {
    $baseSlug = slugify($e['title'] . '-' . $e['city']);
    $e['slug'] = $baseSlug;
    $e['category'] = 'Lifestyle & Festive';
    
    $stmt->execute([
        ':title' => $e['title'],
        ':slug' => $e['slug'],
        ':category' => $e['category'],
        ':event_type' => $e['event_type'],
        ':start_date' => $e['start_date'],
        ':end_date' => $e['end_date'],
        ':date_display' => $e['date_display'],
        ':venue' => $e['venue'],
        ':city' => $e['city'],
        ':state' => $e['state'],
        ':footfall' => $e['footfall'],
        ':gentry' => $e['gentry'],
        ':timings' => $e['timings'],
        ':location_type' => $e['location_type'],
        ':layout_type' => $e['layout_type'],
        ':fan_charge' => $e['fan_charge'],
        ':price_shopping_canopy' => $e['price_shopping_canopy'],
        ':price_shopping_table1' => $e['price_shopping_table1'],
        ':price_shopping_table2' => $e['price_shopping_table2'],
        ':price_food_canopy' => $e['price_food_canopy'],
        ':price_food_table2' => $e['price_food_table2'],
        ':price_promotional' => $e['price_promotional'],
        ':daily_stall_price' => $e['daily_stall_price'],
        ':total_stalls' => $e['total_stalls'],
        ':available_stalls' => $e['available_stalls'],
        ':booked_stalls' => $e['booked_stalls'],
        ':image_url' => $e['image_url'],
        ':description' => $e['description'],
        ':is_featured' => $e['is_featured']
    ]);
    $insertedCount++;
}

echo "[OK] Successfully seeded {$insertedCount} events into database.\n";

// 3. Seed A Couple of Sample Real Bookings for Admin Dashboard Preview
$checkBooking = $pdo->query("SELECT COUNT(*) FROM bookings")->fetchColumn();
if ($checkBooking == 0) {
    $firstEvent = $pdo->query("SELECT * FROM events LIMIT 1")->fetch();
    if ($firstEvent) {
        $insBooking = $pdo->prepare("
            INSERT INTO bookings (
                booking_number, event_id, customer_name, business_name, mobile, whatsapp,
                email, address, category_name, stall_type, start_date, end_date,
                days_count, stalls_count, price_per_day, addons_total, total_amount,
                notes, status, whatsapp_sent
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'confirmed', 1)
        ");
        $insBooking->execute([
            'EXPO-BK-202610-001',
            $firstEvent['id'],
            'Ritu Verma',
            'Aroma Glow Soy Candles',
            '9876543210',
            '9876543210',
            'rituv@aromaglow.com',
            'Sector 45, Gurugram',
            'Candles & Soaps',
            'Shopping Canopy (2 Tables + 2 Chairs + light)',
            $firstEvent['start_date'],
            $firstEvent['end_date'],
            1,
            1,
            5000,
            300,
            5300,
            'Need corner stall near main entrance'
        ]);
        echo "[OK] Sample verified booking seeded.\n";
    }
}

echo "=== Seeding Completed Successfully! ===\n";
